import Head from "next/head";
import tw from "twin.macro";
import styled from "styled-components";
import TopProducts from "../components/Home/TopProducts";
import Instagram from "../components/Home/Instagram";
import PriceListForm from "../components/Forms/PriceListForm";
import Banner from "../components/Banner";
import Clients from "../components/Home/Clients";
import HeroCarousel from "../components/Home/HeroCarousel";

const Main = tw.main`
  max-w-screen-xl 
  mt-24 
  px-8 
  overflow-hidden
  xl:px-16 
  mx-auto
  space-y-10
`;

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroCarousel />

      <Main>
        <TopProducts />
        <Instagram />
        <PriceListForm />
        <Banner />
        <Clients />
      </Main>
    </div>
  );
}
