import React from "react";
import Head from "next/head";
import styled from "styled-components";
import tw from "twin.macro";
import Image from "next/image";
import { Main, Container, H3 } from "../../../styles/Common";
import Link from "../../../components/Link";
import { getCategories, getSubcategory } from "../../../utils/api";
import { getStrapiMedia } from "../../../utils/media";

const Products = styled.div`
  width 100%;
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(230px, 1fr));
  gap: 1rem;
`;

const ProductWrapper = tw.div`  
  flex 
  flex-col 
  items-center
  pb-5
`;

const ProductImage = tw(Image)`
  bg-gray-300 
  rounded-md 
  object-cover 
  w-full
`;

const CategoriesPage = ({ data, capitalizedSlug }) => {
  console.log(data, capitalizedSlug);

  return (
    <>
      <Head>
        <title>Inflables Carcajadas - {capitalizedSlug}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Container>
          <H3>{capitalizedSlug}</H3>
          <Products>
            <ProductWrapper>
              <Link href="/productos/publicitarios/toldos">
                <ProductImage
                  alt="img"
                  src="https://picsum.photos/id/1049/230/230"
                  width="230"
                  height="230"
                />
              </Link>
              <p>Toldos</p>
            </ProductWrapper>
          </Products>
        </Container>
      </Main>
    </>
  );
};

export async function getStaticProps({ params }) {
  const categoryName = params.category;
  const [data, meta, capitalizedSlug] = await getSubcategory(categoryName);

  return { props: { data, meta, capitalizedSlug } };
}

export async function getStaticPaths() {
  const call = await getCategories();
  const categories = call.data;
  return {
    paths: categories.map(_product => {
      return {
        params: { category: _product.attributes.slug },
      };
    }),
    fallback: false,
  };
}

export default CategoriesPage;
